In [11]:
import numpy as np
import tensorflow as tf
import cv2 as cv

In [13]:
x = np.random.normal(size=[1,4]).astype('float32')
x

array([[-0.88085353, -0.57124865,  1.9511936 , -1.32246   ]],
      dtype=float32)

In [16]:
init = tf.keras.initializers.RandomNormal()

In [18]:
w1 = tf.Variable(init(shape=[4,3]))
b1 = tf.Variable(init(shape=[1,3]))
w2 = tf.Variable(init(shape=[3, 2]))
b2 = tf.Variable(init(shape=[1,2]))

In [19]:
@tf.function
def forward(x, w, b , activation):
    return activation(tf.matmul(x, w)+b)

In [21]:
h = forward(x, w1, b1 , tf.nn.sigmoid)
y = forward(h , w2 , b2 , tf.nn.softmax)
print(y)

tf.Tensor([[0.48760623 0.51239383]], shape=(1, 2), dtype=float32)


In [3]:
a = tf.constant(np.array([0.5, 0.2, 0.7 , 0.2 , 0.3, 0.4, 0.9 , 0.1, 0.1]).reshape([3,3]))
a

<tf.Tensor: shape=(3, 3), dtype=float64, numpy=
array([[0.5, 0.2, 0.7],
       [0.2, 0.3, 0.4],
       [0.9, 0.1, 0.1]])>

In [6]:
rmeans = tf.reduce_mean(a , axis = 0)
rmeans

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([0.53333333, 0.2       , 0.4       ])>

Edge Detection

In [21]:
img.dtype

dtype('uint8')

In [25]:
img = cv.imread('./data/photo.jpg')
img = img.astype('float32')
grays = tf.constant([[0.3], [0.59] ,[0.11]])
imgt = tf.constant(img)

x = tf.matmul(imgt , grays)
x.shape

y = tf.constant(x)
filter = tf.Variable(np.array([[-1,-1,-1],[-1,8,-1],[-1,-1,-1]]).astype('float32'))

In [28]:
x.shape

TensorShape([600, 600, 1])

In [26]:
y.shape

TensorShape([600, 600, 1])

In [27]:
y_reshaped = tf.reshape(y , [1,600,600,1])
filter_reshaped = tf.reshape(filter , [3,3,1,1])

In [47]:
y_conv = tf.nn.convolution(y_reshaped, filter_reshaped)

In [48]:
y_conv = np.array(y_conv).squeeze()

In [49]:
cv.imwrite('./data/gray.png',np.array(x))
cv.imwrite('./data/lines.jpeg' , np.array(y_conv))

True